### ISSUE TITLE
Icon-font not up to date

### ISSUE THREAD

**Issue by ChristophTr** [wagtail/wagtail-react-streamfield#39]
Looks to me like the icon-font used in Wagtail 2.5.1 is not represented by the wagtail.woff that comes with the plugin. Specifically icons for subscript and superscript of the Draftail-Editor are missing.

**Comment by BertrandBordage** [comment]
Fixed by c040db0395a0356b51d2303ddb8b376f1ac14877.
Will be released in a new version later today!
